import { Platform, StyleSheet } from "react-native";
import colors from "../../Color";

export const styles = (color) =>
  StyleSheet.create({
    screen: {
      height: "100%",
      backgroundColor: colors[color][50],
      flex: 1,
    },
    titleView: {
      paddingVertical: 8,
      marginVertical: 48,
      zIndex: 2,
      paddingTop: 32,
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-around",
      alignItems: "stretch",
    },
    titleText: {
      margin: "auto",
      fontSize: 48,
      fontWeight: "bold",
      color: colors[color][900],
    },
    TouchableView: {
      borderRadius: 48,
      padding: 8,
      display: "flex",
      justifyContent: "space-evenly",
      alignItems: "center",
      marginHorizontal: 4,
      backgroundColor: colors[color][100],
      position: "absolute",
      bottom: 32,
      right: 32,
      shadowColor: colors[color][100],
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.23,
      shadowRadius: 2.62,
      elevation: 4,
    },
    icon: {
      color: colors[color][900],
      padding: 4,
    },
    form: {
      width: "85%",
      borderRadius: 18,
      alignSelf: "center",
      position: "absolute",
      margin: 24,
      bottom: 72,
      backgroundColor: colors[color][100],
      zIndex: 4,
      elevation: Platform.OS === "android" ? 50 : 0,
      padding: 24,
      flex: 1,
    },
    label: {
      margin: "auto",
      fontSize: 24,
      color: colors[color][900],
    },
    input: {
      margin: "auto",
      fontSize: 24,
      color: colors[color][900],
      padding: 12,
      marginVertical: 16,
      borderWidth: 1,
      borderRadius: 8,
      borderColor: colors[color][400],
      borderStyle: "dashed",
    },
    card: {
      height: 64,
      width: "100%",
      padding: 18,
      marginVertical: 24,
      backgroundColor: colors[color][200],
      borderColor: colors[color][900],
      borderRadius: 12,
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      alignContent: "space-between",
      shadowColor: colors[color][100],
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.23,
      shadowRadius: 2.62,
      elevation: 4,
      zIndex: 2,
    },
    cardText: {
      fontSize: 18,
      color: colors[color][900],
      fontWeight: "900",
    },
    chooser: {
      width: "100%",
      marginVertical: 16,
      borderWidth: 1,
      borderRadius: 8,
      borderColor: colors[color][400],
      borderStyle: "dashed",
    },
    picker: {
      padding: 24,
    },
    item: {
      color: colors[color][800],
      opacity: 0.6,
      fontFamily: "monospace",
      letterSpacing: 2,
    },
    dividerText: {
      alignSelf: "center",
      color: colors[color][800],
      opacity: 0.6,
      letterSpacing: 4,
    },
    divider: {
      borderBottomColor: colors[color][900],
      opacity: 0.2,
      marginHorizontal: -24,
      borderBottomWidth: 1,
      marginVertical: 16,
    },
    cardIcon: {
      maxWidth: "50%",
      paddingLeft: 2,
      marginLeft: "auto",
      fontSize: 24,
      marginTop: -2,
    },
    customButton: {
      backgroundColor: colors[color][200],
      marginHorizontal: -24,
      marginBottom: -24,
      marginTop: 8,
      padding: 24,
      borderRadius: 16,
      borderTopEndRadius: 0,
      borderTopStartRadius: 0,
    },
    buttonText: {
      alignSelf: "center",
    },
    inputIcon: {
      margin: "auto",
      fontSize: 24,
      color: colors[color][900],
      padding: 12,
      marginVertical: 16,
      borderWidth: 1,
      borderRadius: 8,
      borderColor: colors[color][400],
      borderStyle: "dashed",
    },
    spinner: {
      margin: "auto",
      position: "absolute",
      alignSelf: "center",
      top: 0,
      bottom: 0,
      left: 0,
      right: 0,
    },
  });
